version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
volumes:
  db_data:
