version: '3'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5555:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always
    # command: ["sleep", "infinity"]
  web:
    build: .
    environment:
      DATABASE_HOST: db
    ports:
      - "80:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
volumes:
  db_data:
