services:
  web:
    build:
      context: .
      args:
        RAILS_ENV: ${RAILS_ENV}
    environment:
      DATABASE_HOST: db
    ports:
      - "80:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - minio
    restart: always
  
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5555:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always
    # command: ["sleep", "infinity"]

  minio:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z-cpuv1
    ports:
      - "9001:9001"  # Web UI
    environment:
      MINIO_ROOT_USER: minioaccess
      MINIO_ROOT_PASSWORD: miniosecret
    volumes:
      - ./minio_data:/data
    restart: always
    command: server /data --console-address ":9001"

volumes:
  db_data:
  minio_data:
