default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  user: postgres
  database: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

production:
  <<: *default


